site_name: "CISC 322 Group 35"
site_url: "https://obeia.github.io"
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
nav:
  - Home: index.md
  - Apollo Resources: assignment0.md
  - Conceptual Architecture: assignment1.md
  - Concrete Architecture: assignment2.md
  - Enhancement Proposal: assignment3.md
markdown_extensions:
  - tables
  - md_in_html
  - pymdownx.caret
